export interface TimeSlot {
  subject: string;
  startTime: string; // "HH:MM"
  endTime: string; // "HH:MM"
  days: string[]; // ["Monday", "Tuesday", ...]
  room?: string;
  teacher?: string;
  type: 'lecture' | 'lab' | 'tutorial' | 'seminar' | 'break' | 'lunch' | 'activity' | 'other';
}

export interface ParsedTimetable {
  institution?: string;
  department?: string;
  semester?: string;
  division?: string;
  timeSlots: TimeSlot[];
  confidence: 'high' | 'medium' | 'low';
  notes?: string;
}

export interface StudentProfile {
  studentName?: string;
  role?: 'student' | 'teacher' | 'parent' | 'other';
  course?: string;
  semester?: string;
  wakeUpTime: string; // "06:00"
  sleepTime: string; // "22:00"
  preferredStudyTime: 'morning' | 'afternoon' | 'evening' | 'night';
  dailyGoalHours: number;
  weakSubjects: string[];
  strongSubjects: string[];
  travelTimeMinutes: number;
  coachingTimings?: string; // "17:00-19:00" or empty
  gymTiming?: string; // "07:00-08:00" or empty
  homeworkTimeMinutes: number;
  breakPreference: 'short' | 'long'; // short = 25/5, long = 50/10
  revisionPreference: 'morning' | 'night' | 'split';
  isOnboarded: boolean;
}

export interface Exam {
  id: string;
  subject: string;
  date: string; // "YYYY-MM-DD"
  description?: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
}

export interface Assignment {
  id: string;
  title: string;
  subject: string;
  dueDate: string; // "YYYY-MM-DD"
  priority: 'low' | 'medium' | 'high' | 'critical';
  completed: boolean;
}

export interface ScheduleItem {
  id: string;
  startTime: string; // "06:00"
  endTime: string; // "06:15"
  label: string; // "Wake Up" or "Study: Mathematics"
  type: 'wake_up' | 'school_college' | 'study' | 'homework' | 'revision' | 'break' | 'meal' | 'travel' | 'sleep' | 'other';
  subject?: string;
  description?: string;
  completed?: boolean;
}

export interface AISchedule {
  date: string; // "YYYY-MM-DD"
  timeline: ScheduleItem[];
  smartTodos: string[]; // List of tasks generated by AI
  recommendations: string[]; // List of tips/recommendations
  subjectAnalysis: {
    subject: string;
    focusArea: string;
    suggestedDurationMinutes: number;
  }[];
  focusPlan: string; // Focused work style suggestion for the day
}

export interface Task {
  id: string;
  title: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  completed: boolean;
  dueDate?: string; // "YYYY-MM-DD"
  subject?: string;
  isAiGenerated?: boolean;
  isRecurring?: boolean;
}

export interface FocusSession {
  id: string;
  date: string; // "YYYY-MM-DD"
  subject: string;
  durationMinutes: number;
  completed: boolean;
  focusScore: number; // 1-100
  ambientSoundUsed?: string;
}

export interface UserTheme {
  name: 'light' | 'dark' | 'glass' | 'cyberpunk' | 'amoled' | 'ocean' | 'forest' | 'sunset' | 'apple';
}
